---

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

docker_service_enabled: true
docker_restart_handler_state: restarted
docker_service_state: started

# Docker compose 
docker_install_compose: true
docker_compose_version: "1.25.4"
docker_compose_path: /usr/local/bin/docker-compose