---
- name: Install required system packages
  apt:
    name: software-properties-common
    state: present
    update_cache: yes


- name: Add Openjdk repository
  apt_repository:
    repo: ppa:openjdk-r/ppa


- name: Install required system packages
  apt:
    name: openjdk-8-jdk
    state: latest
    update_cache: yes
