---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Setup docker with Homebrew
  homebrew:
    name: docker
    update_homebrew: yes
  when:
    - homebrew_check.stat.exists


- name: Setup docker
  become: yes
  block:
    - name: Remove old docker version if installed
      apt:
        name:
          - docker
          - docker-engine
        state: absent

    - name: Update Apt cached
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

    - name: Install Docker.
      apt:
        name: "{{ docker_package }}"
        state: "{{ docker_package_state }}"
      notify: restart docker
  when:
    - not homebrew_check.stat.exists


- name: Ensure Docker is started and enabled at boot.
  become: yes
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
