---
- name: Remove old neovim & vim packages
  apt:
    name:
      - vim
    state: absent

- name: Install necessary tools
  apt:
    name:
      - software-properties-common
    state: latest
    update_cache: yes


- name: Add neovim repository
  apt_repository:
    repo: ppa:neovim-ppa/stable


- name: Install neovim packages
  apt:
    name: 'neovim'
    state: latest
    update_cache: yes

