" Auto completion plugin
"   Requirement: node: 10.12+
"   
"'''''''''''''''''''''''''''''''''''''''''''''

Plug 'neoclide/coc.nvim', {'branch': 'release'}

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
map <silent> [g <Plug>(coc-diagnostic-prev)
map <silent> ]g <Plug>(coc-diagnostic-next)
