" Vim Markdown Preview
"    Usage: Ctrl-p
"
" - Requirement: brew install markdown grip
"'''''''''''''''''''''''''''''''''''''''''''''

Plug 'JamshedVesuna/vim-markdown-preview'
let vim_markdown_preview_browser='Google Chrome'
let vim_markdown_preview_github=1
let vim_markdown_preview_temp_file=1
let vim_markdown_preview_toggle=1
