---

- name: Clone oh-my-zsh source
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ om_zsh_path }}"


- name: Config zshrc file
  copy:
    src: "files/zshrc.yml"
    dest: "{{ zshrc_path }}"


- name: Config p10k.zsh file
  copy:
    src: "files/p10k.zsh.yml"
    dest: "{{ p10k_path }}"


- name: Clone auto suggestion plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ om_zsh_path }}/custom/plugins/zsh-autosuggestions"


- name: Clone syntax highlight plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ om_zsh_path }}/custom/plugins/zsh-syntax-highlighting"


- name: Clone powerlevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    depth: 1
    dest: "{{ om_zsh_path }}/custom/themes/powerlevel10k"


- name: Set zsh as default shell
  become: yes
  user:
    name: "{{ ansible_user }}" 
    shell: /usr/bin/zsh