---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Install curl with Homebrew
  homebrew:
    name: curl
    state: latest
    update_homebrew: yes
  when:
    - homebrew_check.stat.exists


- name: Install curl 
  become: yes
  apt:
    name: curl
    state: latest
    update_cache: yes
  when:
    - not homebrew_check.stat.exists

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    creates: "~/.nvm/nvm.sh"
    chdir: "$HOME"


- name: Get default shell
  shell: env |grep SHELL | cut -d '=' -f 2
  register: sl

- name: Setup .zshrc
  lineinfile:
    path: ~/.zshrc
    line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
    create: yes
  when: "{{ 'zsh' in sl.stdout }}"

- name: source bashrc file
  shell: source ~/.zshrc
  when: "{{ 'zsh' in sl.stdout }}"

- name: Install default node
  shell: "nvm install {{ default_node_version }}"
  args:
    executable: "{{ sl.stdout }}"

