---
- name: Ensuring Homebrew Is Installed
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check

- name: Install curl with Homebrew
  homebrew:
    name: curl
    state: latest
    update_homebrew: yes
  when:
    - homebrew_check.stat.exists


- name: Install curl 
  become: yes
  apt:
    name: curl
    state: latest
    update_cache: yes
  when:
    - not homebrew_check.stat.exists

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | bash
  args:
    executable: /bin/bash
    creates: "~/.nvm/nvm.sh"


- name: Add NVM to nvm_profile
  blockinfile:
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    marker_begin: "Load installed nvm - START"
    marker_end: "Load installed nvm - END"
    create: yes
    mode: 0644
    path: "~/.bashrc"
    state: present


- name: Reload terminal environment
  shell: 'eval "$(exec /usr/bin/env -i "${SHELL}" -l -c "export")"'
  args:
    executable: /bin/bash

- name: Install default node
  shell: "nvm install {{ default_node_version }}"
  args:
    executable: /bin/bash

