---
- name: Install fontConfig
  apt:
    name: fontconfig
    state: present
    update_cache: yes

- name: Create font folder
  file:
    path: "~/.local/share/fonts"
    state: directory


- name: Install font
  copy:
    src: "{{ item }}"
    dest: "~/.local/share/fonts/"
  with_fileglob:
    - "files/*.ttf"


- name: Clear and regenereate font cache
  command: fc-cache -f -v
